version: 2

############################################################################

jobs:
   build:
      docker:
         - image: jiteshsojitra/docker-headless-vnc-container
      environment:
         - zimbra.version: 8.8.0_GA
         - DISPLAY: :1.0
         - XDG_CONFIG_DIRS=/etc/xdg
         - DESKTOP_SESSION=xfce
         - XDG_DATA_DIRS=/usr/share/xfce4:/usr/local/share:/usr/share:/usr/share
         - XDG_CURRENT_DESKTOP=XFCE
         - COLORTERM=xfce4-terminal
      working_directory: ~/zm-selenium
      steps:
         - checkout
         - run:
              name: Start xfce
              command: startxfce4
         - run:
              name: Environment variable
              command: env
         - run:
              name: Checkout dependent repos
              command: bash .circleci/checkout-repos.sh
         - run:
              name: Compile zimbra native
              working_directory: ~/zm-mailbox/native
              command: ant publish-local -Ddev.home=$HOME -Dzimbra.buildinfo.version=$zimbra.version
         - run:
              name: Compile zimbra common
              working_directory: ~/zm-mailbox/common
              command: ant publish-local -Ddev.home=$HOME -Dzimbra.buildinfo.version=$zimbra.version
         - run:
              name: Run selenium tests
              working_directory: ~/zm-selenium
              command: ant Run-ExecuteHarnessMain -Duser.home=$HOME -Dpattern startatt.tests.competitors -Dgroups always,L0
         - store_artifacts:
              path: ~/zm-selenium/test-output

workflows:
   version: 2
   build_selenium:
      jobs:
         - build

############################################################################