version: 2

############################################################################

jobs:
   build:
      docker:
         - image: jiteshsojitra/docker-headless-vnc-container
      environment:
         - zimbra.version: 8.8.0_GA
      working_directory: ~/zm-selenium
      steps:
         - checkout
         - run:
              name: Checkout dependent repos
              command: bash .circleci/checkout-repos.sh
         - run:
              name: Compile zm-mailbox/native
              working_directory: ~/zm-mailbox/native
              command: ant publish-local -Ddev.home=$HOME -Dzimbra.buildinfo.version=$zimbra.version
         - run:
              name: Compile zm-mailbox/common
              working_directory: ~/zm-mailbox/common
              command: ant publish-local -Ddev.home=$HOME -Dzimbra.buildinfo.version=$zimbra.version
         - run:
              name: Run selenium tests
              working_directory: ~/zm-selenium
              command: ant Run-ExecuteHarnessMain -Duser.home=$HOME -Dpattern startatt.tests.competitors -Dgroups always,L0
         - test-output:
              path: ~/zm-selenium/test-output

workflows:
   version: 2
   build_selenium:
      jobs:
         - build

############################################################################