version: 2

############################################################################

jobs:
   build:
      docker:
         - image: consol/ubuntu-xfce-vnc
      steps:
         - checkout
              name: Checking out dependencies
         - run:
              name: Install pre-requsites
              command: .circleci/prepare-box.sh
	- run:
              name: Checkout dependent repos
              command: .circleci/checkout-repo.sh
	- run:
               name: Compile zm-mailbox
               working_directory: ~/zm-mailbox
               command: ant publish-local-all -Dzimbra.buildinfo.version=8.8.0_GA
          - run:
               name: Run selenium tests
               working_directory: ~/zm-selenium
               command: ant Run-ExecuteHarnessMain -Dpattern startatt.tests.competitors -Dgroups always,L0
         - run:
		name: Persist to workspace
              root: ../..
              paths: ~/zm-selenium/test-output/*

workflows:
   version: 2
   build_selenium:
      jobs:
         - build

############################################################################