version: 2

############################################################################

jobs:
   build:
      docker:
         - image: jiteshsojitra/docker-headless-vnc-container
           entrypoint: /dockerstartup/vnc_startup.sh
      environment:
         - zimbra_version: 8.8.0_GA
      working_directory: ~/zm-selenium
      steps:
         - checkout
         - add_ssh_keys:
              fingerprints: 47:28:e4:00:8e:67:f5:3e:42:c0:85:2c:84:8f:d1:3e
         - run:
              name: Checkout dependent repos
              command: bash .circleci/checkout-repos.sh
         - run:
              name: Compile zimbra native
              working_directory: ~/zm-mailbox/native
              command: ant publish-local -Ddev.home=$HOME -Dzimbra.buildinfo.version=$zimbra_version
         - run:
              name: Compile zimbra common
              working_directory: ~/zm-mailbox/common
              command: ant publish-local -Ddev.home=$HOME -Dzimbra.buildinfo.version=$zimbra_version
         - run:
              name: Execute selenium tests
              working_directory: ~/zm-selenium
              command: ant Run-ExecuteHarnessMain -Duser.home=$HOME -Dpattern projects.ajax.tests.mail.folders -Dgroups always,L0
         - persist_to_workspace:
              root: ~/zm-selenium/test-output
              paths:
                 - ~/zm-selenium/workspace
         - store_artifacts:
              path: ~/zm-selenium/test-output
         - store_test_results:
              path: ~/zm-selenium/test-output

   execute:
      working_directory: ~/zm-selenium
      steps:
         - attach_workspace:
              at: ~/zm-selenium/workspace

##############################

workflows:
   version: 2
   SeleniumCI:
      jobs:
         - build
         - execute:
              requires:
                 - build

############################################################################